ray_init:
  num_cpus: int #TBD

actor_rollout_ref:
  model:
    path: str # TBD!
  actor:
    strategy: bool # "fsdp", "fsdp2", "megatron"
    use_kl_loss: bool # TBD!
  rollout:
    mode: null

critic:
  strategy: null # ???

reward_model:
  enbale: bool # TBD!
  strategy: str # "fsdp", "fsdp2", "megatron"

trainer:
  n_gpus_per_node: int # TBD!
  nnodes: int # TBD!

algorithm:
  use_kl_in_reward: bool # TBD!

data:
  trust_remote_code: null #???

  train_files: str # TBD!
  val_files: str # TBD!

  custom_cls:
    path: str # TBD!
    name: str # TBD!

  # sampler
  shuffle: true