project_name: init_policy
entity_name: DRL_Project_Group
run_name: ''

train:
  load_path: null
  save_path: /data/mqj/datasets/
  epoch: 100
  val_interval: 10

TransitionModel:
  state_dim: 3584
  goal_dim: 1536
  embed_dim: 2048 # or others?
  num_attn_layers: 12
  num_heads: 16
  activation: ReLU

Agent:
  num_sce_type: 2 # 0 for Asking questions and 1 for Searching for things
  latent_action_dim: int # TBD!
  num_attn_layers_first: int # TBD!
  num_heads_first: int # TBD!
  num_attn_layers_second: int # TBD!
  num_heads_second: int # TBD!

Action_encoder:
  action_encoder_backbone: roberta-base # deberta-base , electra-base
  action_encoder_cache_dir: null

Goal_encoder:
  goal_encoder_backbone: roberta-base # deberta-base , electra-base
  goal_encoder_cache_dir: null

train_init_policy:
  trainer_name: str # BC or MCP
  loss_coef_alpha: float # TBD!
  loss_coef_beta: float # TBD!
  trial_times: int # TBD!
  x_range_min: float # TBD!
  x_range_max: float # TBD!
  y_range_min: float # TBD!
  y_range_max: float # TBD!