# ===================
# ====== task ======
# ===================
task_split: "test" # "train" or "test"
eval_sample_mode: "sequential" # "random" or "sequential"
max_steps: 20 # max_steps of AitW General should be 10; of AitW Web Shopping should

# ===================
# ====== token ======
# ===================
huggingface_token: ''
wandb_key: ''
gemini_key: ''

# ===================
# ====== algo ======
# ===================
policy_lm: '/home/mqj/Auto-UI-Base'
critic_lm: 'roberta-base'
capacity: 17000 # replay buffer size
bsize: 1 # number of emulators parallelly on the machine
rollout_size: 16 # how many trajectories to collect between training iterations (should be multiple of bsize)
warmup_iter: 0 # how many iterations to only collect data and evaluate before training
trajectory_critic_epochs: 5
max_grad_norm: 0.01
gamma: 0.95
gae_lambda: 0.50

# ===================
# ====== agent ======
# ===================
use_lora: False
agent_name: "autoui" # "autoui" only
do_sample: True
tau: 0.10 #soft update parameter
max_new_tokens: 128

# ===================
# ====== log ======
# ===================
record: False # whether you want to record mp4 videos
use_wandb: True
entity_name: ''
project_name: ''

# ===================
# ====== path ======
# ===================
# query by: echo $ANDROID_AVD_HOME
android_avd_home: '/data/mqj/avd'
# query by: which emulator
emulator_path: '/home/mqj/.android/emulator/emulator'
# query by: which adb
adb_path: '/home/mqj/.android/platform-tools/adb'
cache_dir: '/home/mqj/.cache'
assets_path: '/home/mqj/main_digiq_mb/digiq_mb/digiq/environment/android/assets/task_set'
click_icon_path: '/home/mqj/main_digiq_mb/digiq_mb/assets/click.png'
