project_name: train_transition
entity_name: DRL_Project_Group
run_name: ''

train:
  load_path: null
  save_path: /data/mqj/models/full_transition
  epoch: 1500 # more for transformer (~1500), less for MLP (~500)
  val_interval: 10
  K: 1 # nb of models
  seed: 3047
  bagging: false # to activate bootst sampling

TransitionModel:
  state_dim: 3584
  action_dim: 1536
  goal_dim: 768
  embed_dim: 2048
  num_attn_layers: 0
  num_heads: 4
  activation: ReLU

Action_encoder:
  action_encoder_backbone: roberta-base # deberta-base , electra-base
  action_encoder_cache_dir: null

Goal_encoder:
  goal_encoder_backbone: roberta-base
  goal_encoder_cache_dir: null

data:
  data_path_general: /data/mqj/datasets/rl/general-ft.pt
  data_path_web_shop: /data/mqj/datasets/rl/webshop-ft.pt
  batch_size: 256
  capacity: 500000
  train_ratio: 0.8
  val_ratio: 0.2

tools:
  wandb_key: e0eb5f8fe893dc0119123578457a29ce75167b03