project_name: train_value
entity_name: DRL_Project_Group
run_name: ''

train:
  load_path: null
  save_path: /content/drive/MyDrive/College/Tsinghua/Deep_Reinforcement_Learning/digiq_mb/train_value_model
  epoch: 100
  val_interval: 10

TransitionModel:
  state_dim: 3584
  goal_dim: 1536
  embed_dim: 2048 # or others?
  action_dim: 1536
  num_attn_layers: 12
  num_heads: 16
  activation: ReLU

Action_encoder:
  action_encoder_backbone: roberta-base # deberta-base , electra-base
  action_encoder_cache_dir: null

Goal_encoder:
  goal_encoder_backbone: roberta-base
  goal_encoder_cache_dir: null

data:
  data_path: /content/drive/MyDrive/College/Tsinghua/Deep_Reinforcement_Learning/digiq_mb/datasets/general-origin-uitars.pt
  batch_size: 512
  capacity: 500000
  train_ratio: 0.8
  val_ratio: 0.2

tools:
  wandb_key: e0eb5f8fe893dc0119123578457a29ce75167b03