project_name: train_value
entity_name: DRL_Project_Group
run_name: ''

train:
  load_path: null
  save_path: /home/qinweima/digiq_mb/digiq/checkpoints/train_value
  epoch: 10
  val_interval: 10

ValueModel:
  state_dim: 3584
  goal_dim: 1536
  embed_dim: 2048 # or others?
  num_attn_layers: 12
  num_heads: 16
  activation: ReLU

Goal_encoder:
  goal_encoder_backbone: roberta-base
  goal_encoder_cache_dir: /srv/local/xsm/hf_cache/roberta-base

data:
  data_path: /home/qinweima/digiq_mb/digiq/data/general.pt
  batch_size: 512
  capacity: 500000
  train_ratio: 0.8
  val_ratio: 0.2

tools:
  wandb_key: e0eb5f8fe893dc0119123578457a29ce75167b03